name: 'Sphinx Bot'
description: 'Sphinx Bot Github Action to send messages to previously created bots in the Sphinx platform.'
author: 'Stakwork & Sphinx'

branding:
  icon: message-square
  color: blue

# Define your inputs here.
inputs:
  tribe_url:
    description: 'URL of the tribe you want to post to'
    required: true
  bot_id:
    description: 'BOT ID of the tribe you want to post to'
    required: true
  bot_secret:
    description: 'BOT Secret of the tribe you want to post to'
    required: true
  chat_uuid:
    description: 'Chat UUID of the tribe you want to post to'
    required: true
  bot_message:
    description: 'Message to post'
    required: true

# Define your outputs here.
outputs:
  message: 'Response from the bot'
  success: true

runs:
  using: node20
  main: dist/index.js
